name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: "1.16.x"
            otp: "26.x"
          - elixir: 1.15.x
            otp: "25.x"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile
      - name: Compile
        run: mix compile --warnings-as-errors

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: "1.16.x"
            otp: "26.x"
          - elixir: 1.15.x
            otp: "25.x"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile
      - name: Run tests
        run: mix test

  check-formatted:
    name: Check Formatted
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: "1.16.x"
            otp: "26.x"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile
      - name: Check formatted
        run: mix format --check-formatted
